### ISSUE TITLE
Blog post about metabase graphs of RTD/Sphinx usage

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/blog#175]
We have done lots of interesting data collection in our metabase research. It would be neat to publish this, and share some of this data with the community. Not a ton of direction here, but curious what we can find in the data!

A couple ideas:

* What are the most popular sphinx extensions?
* Graphs of version usage over time. How do Sphinx/mkdocs/etc. versions get updated after a release?

This could also be a really great Twitter thread to start with, then migrate it into a blog post as we get engagement there.

**Comment by humitos** [comment]
> What are the most popular sphinx extensions?

I created this Metabase query for this: https://ethicalads.metabaseapp.com/question/266-sphinxcontrib-extensions-used?days=7. Note that it only takes into account `sphinxcontrib-*` and `sphinx-*` as extensions because that's the easiest way to detect them. However, this is not perfect.

Also, the `sphinx-rtd-theme` is so high that it "breaks" the graphic, so I may need to find a way to skip it and note that into the blog post. I don't know how to do it yet.

**Comment by humitos** [comment]
> Graphs of version usage over time. How do Sphinx/mkdocs/etc. versions get updated after a release?

We already have Sphinx and MkDocs questions:

* `mkdocs`: https://ethicalads.metabaseapp.com/question/245-projects-using-mkdocs-timeserie
* `sphinx`: https://ethicalads.metabaseapp.com/question/250-projects-using-sphinx-timeserie

We also have some other questions for:

* `sphinx-notfound-page`: https://ethicalads.metabaseapp.com/question/243-projects-using-sphinx-notfound-page-timeserie
* `sphinx-hoverxref`: https://ethicalads.metabaseapp.com/question/267-projects-using-sphinx-hoverxref-timeserie
* `jupyter-book`: https://ethicalads.metabaseapp.com/question/242-projects-using-jupyter-book-timeserie

**Comment by humitos** [comment]
I need to sit down and think more about the narrative around these graphics. I don't want to go too deep analyzing them because I'm not statistician, but I think we can answer some general questions and communicate how we are going to use them to make product decisions.
